### ISSUE TITLE
Heading color is incorrect on legend state landing page

### ISSUE THREAD

**Issue by kyleshevlin** [LegendApp/legend-docs#17]
All the headings are a dark color, and many of them can't be seen at all. Here's a screen capture:

![screencapture-legendapp-open-source-state-v3-2024-10-02-08_52_24](https://github.com/user-attachments/assets/292bbf18-0b8b-4094-8691-d5e2b1787b27)

**Comment by jmeistrich** [comment]
Whoa that's wild! What OS/browser are you using? Are you in light or dark mode?

**Comment by kyleshevlin** [comment]
macOS Sonoma 14.4.1, Chrome 129.0.6668.91, light mode.

**Comment by jmeistrich** [comment]
Oh fascinating, it looks correct in Arc and Brave where I tested it, but Chrome does that in light mode... Thanks, I'll fix it!

**Comment by jmeistrich** [comment]
Fixed. Thank you!
