### ISSUE TITLE
Possible mistake in /content/docs/usage/observable.mdx

### ISSUE THREAD

**Issue by SzymonNastaly** [LegendApp/legend-docs#23]
I have just started learning legend-state. I think I found a small mistake in the documentation:
Right now `str$` is not used anywhere in the linked observable. Shouldn't the instances of `arr$` be replaced with `str$`?

https://github.com/LegendApp/legend-docs/blob/f99d395f6609236e0f31920d9211c077c2e26d59/packages/state/src/content/docs/usage/observable.mdx?plain=1#L257-L265

**Comment by jmeistrich** [comment]
Thanks! Fixed, and will publish an update to the site shortly!
